crm/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(TemplateView.as_view(template_name="index.html")), name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('login/submit', views.submit_login, name="submit_login"),
    path('customer/', include("customer.urls"))
]

customer/urls.py
from django.urls import path
from .views import (
    CustomerListView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
)

app_name = "customer"

urlpatterns = [
    path("list/", CustomerListView.as_view(), name="customer-list"),
    path("", CustomerCreateView.as_view(), name="customer-create"),
    path("<int:id>/", CustomerUpdateView.as_view(), name="customer-update"),
    path("<int:id>/delete/", CustomerDeleteView.as_view(), name="customer-delete"),
]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_phone_number(self):
        return f"({self.area_code}) {self.phone_number}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_city(self):
        return f"{self.city} - {self.state}"        

    def get_absolute_url(self):
        return reverse ("customer:customer-update", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse ("customer:customer-delete", kwargs={"id": self.id})

    class Meta:
        db_table = "customer"

customer/forms.py
from django import forms
from .models import Customer

class DateInput(forms.DateInput):
      input_type = "date"

class CustomerForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Nome",
        error_messages={"max_length":"Nome não pode ter mais que 30 caracteres"}
    )
    last_name = forms.CharField(
        label="Sobrenome",
        error_messages={"max_length":"Sobrenome não pode ter mais que 30 caracteres"}
    )
    email = forms.EmailField(label="E-mail")
    birth_date = forms.DateField(label="Data de Nascimento", widget=DateInput(format=('%Y-%m-%d')))
    area_code = forms.RegexField(
        label="DDD",
        regex=r"^\+?1?[0-9]{2}$",
        error_messages={"invalid": "Número de DDD inválido"}
    )
    phone_number = forms.RegexField(
        label="Fone",
        regex=r"^\+?1?[0-9]{8,15}$",
        error_messages={"invalid": "Número de Telefone inválido"}
    )
    country = forms.CharField(label="País")
    state = forms.CharField(label="Estado")
    city = forms.CharField(label="Cidade")

    class Meta:
        model = Customer
        fields = (
            "first_name", "last_name", "email", "birth_date", "area_code", "phone_number",
            "country", "state", "city"
        )

class CustomerDeleteForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ("first_name", "last_name", "email", "birth_date", "area_code", "phone_number",
            "country", "state", "city"
        )

core/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import (
    authenticate, 
    login as django_login,
    logout as django_logout
)
from django.contrib import messages
# Create your views here.
def login(request):
    return render(request, "login.html")

def submit_login(request):
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            django_login(request, user)
            return redirect("index")
        else:
            messages.error(request, "Usuario/Senha inválido. Por favor, tente novamente")
    return redirect("index")

def logout(request):
    django_logout(request)
    return redirect("login")

customer/views.py
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse_lazy
from django.views.generic import (
    ListView, 
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Customer
from .forms import CustomerForm, CustomerDeleteForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Create your views here.
class CustomerListView(ListView):
    template_name = "customer/customer_list.html"
    model = Customer
    paginate_by = 10
    

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            object_list = self.model.objects.filter(
                Q(first_name__contains=name) | Q(last_name__contains=name)
            )
        else:
            object_list =  self.model.objects.all()
        return object_list
    

class CustomerCreateView(CreateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm
    success_url = reverse_lazy("customer:customer-list")

    def form_valid(self, form):
        return super().form_valid(form)

class CustomerUpdateView(UpdateView):        
    template_name = "customer/customer.html"
    form_class = CustomerForm
    success_url = reverse_lazy("customer:customer-list")

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id)

    def form_valid(self, form):
        return super().form_valid(form)

class CustomerDeleteView(DeleteView):        
    model = Customer
    success_url = reverse_lazy("customer:customer-list")

    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id)

core/templates/index.html
{% extends "model-page.html" %}
{% block content %}
<h1>CRM</h1>


{% endblock %}

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >

</head>

<body class="d-flex flex-column">
  <div class="sidenav">
         <div class="login-main-text">
            <h2>CRM<br>Sistema de Gestão de Clientes</h2>            
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form action="submit", method="POST">{% csrf_token %}
                  <div class="form-group">
                     <label>Usuário</label>
                     <input type="text" class="form-control" placeholder="Usuário" name="username">
                  </div>
                  <div class="form-group">
                     <label>Senha</label>
                     <input type="password" class="form-control" placeholder="Senha" name="password">
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                          <div class="alert alert-danger">{{ message }}</div>
                      {% endfor %}

                  {% endif %}
                  <button type="submit" class="btn btn-black">Login</button>
                 
               </form>
            </div>
         </div>
      </div>
</body>
</html>

core/templates/model-footer.html
<div class="container text-center">
    <small class="footer-mycolor">Desenvolvido por Luis Bannwart</small>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">    
    <a class="navbar-brand" href={% url 'index' %}>CRM</a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
        </li>
    </ul>
    <a class="me-2" href="{% url 'logout' %}">Sair</a>
</nav>

core/templates/model-page.html
<!doctype html>
<html lang="pt-br" class="h-100">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shirink-to-fit=no">
    <title>CRM - Gestão de Clientes</title>    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <style>
        main > .container {padding: 60px 15px 0;}
        .footer-mycolor  { color: #fff; }
    </style>
</head>
<body class="d-flex flex-column h-100">
    
<header>
    {% include "model-header.html" %}
</header>

<main class="flex-shrink-0" style="margin-top: 2%">
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</main>

<footer class="footer mt-auto py-3 bg-dark">
    {% include "model-footer.html" %}
</footer>
</body>
</html>

customer/templates/customer/customer.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Clientes</h2>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.erros %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method='POST'>{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

customer/templates/customer/customer_confirm_delete.html
{% extends "model-page.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form method='POST'>{% csrf_token %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col">
                    <p class="h3">Confirma a exclusão do cliente {{ customer.get_full_name }}?</p>
                </div>
            </div>        
            <div class="row justify-content-start">
                <div class="col-4">
                    <button type="submit" class="btn btn-danger">Sim</button>
                </div>
                <div class="col-4">
                <a href="{% url 'customer:customer-list' %}"><button type="button" class="btn btn-primary">Não</button></a>
                </div>
                <div class="col-4"></div>
            </div>
        </div>
    </form>
{% endblock %}

customer/templates/customer/customer_list.html
{% extends "model-page.html" %}
{% load app_tags %}

{% block content %}
    <h2>Clientes</h2>
    <a href="{% url "customer:customer-create" %}"
        <button type="button" class="btn btn-success" style="float: right; margin-bottom: 1rem">Adicionar</button>
    </a>

    <form action="">{% csrf_token %}
        <div class="form-group mb-1">
            <input class="form-control" name="name" placeholder="Buscar por nome..." type="text">
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>

    <table class="table table-bordered mt-4">
    <thead>
        <tr>
        <th scope="col">Nome</th>
        <th scope="col">Cidade</th>
        <th scope="col">Telefone</th>
        <th scope="col">e-mail</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for customer in object_list %}
            <tr>
            <td><a href="{{ customer.get_absolute_url }}">{{ customer.get_full_name }}</a></td>
            <td>{{ customer.get_full_city }}</td>
            <td>{{ customer.get_full_phone_number }}</td>
            <td>{{ customer.email }}</td>
            <form method="get" action="{{ customer.get_delete_url }}">{% csrf_token %}
                <td><button type="submit" class="btn btn-danger">Excluir</button></td>
            </form>
            </tr>
        {% endfor %}
    </tbody>
    </table>    

    <nav aria-label="Page navigation example">
    
    {% if '?' in request.get_full_path %}
        <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page=1">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo; first</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">previous</a></li>
                {% endif %}

                <li class="page-item disabled"><span class="current page-link">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span></li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">next</a></li>
                    <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">next</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">last &raquo;</a></li>
                {% endif %}
        </ul>
    {% else %}
        <ul class="pagination">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">&laquo; first</a></li>
                    <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">previous</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo; first</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">previous</a></li>
                {% endif %}

                <li class="page-item disabled"><span class="current page-link">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span></li>

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">next</a></li>
                    <li class="page-item"><a class="page-link" href="?{% param_replace page=paginator.num_pages %}">last &raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">next</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">last &raquo;</a></li>
                {% endif %}
            {% endif %}
        </ul>
    {% endif %}
    </nav>

{% endblock %}